const theme = {
  default: {
    id: "T_001",
    name: "Moonlight Drive",
    colors: {
      primary: "#FFF3DD",
      secondary: "#142C69",
      windowColor: "#FFF3DD",
      background: "#142C69",
      boxShadow: "FFFFFF",
      barColor: "#FFF3DD",

      bodyColor: "#142C69",
      bodyBackground: "#142C69 url('./pixels-dark.svg') top left",
      containerWindowColor: "#FFF3DD",
      menuBackgroundColor: "#FFF3DD",
      svgIconColor: "#142C69",
      menuBorderColor: "#142C69",
      menuBoxShadow: "inset 1px 1px 0 0 #fff, 0 8px 0 0 rgb(0 0 0 / 20%)",
      addresBarBackground: "#FFF3DD",
      addresBarColor: "#142C69",
      addresBarSquaresColor: "#FFF3DD",
      addresBarSquaresBorderColor: "#142C69",
      addresBarSquaresBoxShadow: "inset 1px 1px 0 0 #fff",
      dashboardBackground: "url(./pixels-light.svg) top left",
      text: {
        primary: "#142C69",
        secondary: "#5c5a57",
        barColor: "#142C69",
      },
      button: {
        text: "#FFFFFF",
        background: "#000000",
      },
      link: {
        text: "teal",
        opacity: 1,
      },
    },
    font: "Tinos",
  },
  alpineNight: {
    id: "T_001",
    name: "Alpine Night",
    colors: {
      primary: "#0F1D19",
      secondary: "#142C69",
      windowColor: "#0F1D19",
      background: "#142C69",
      boxShadow: "FFFFFF",
      barColor: "#0F1D19",

      bodyColor: "#44DEB5",
      bodyBackground: "#44DEB5 url('./pixels-dark.svg') top left",
      containerWindowColor: "#0F1D19",
      menuBackgroundColor: "#0F1D19",
      svgIconColor: "#fff",
      menuBorderColor: "#fff",
      menuBoxShadow: "0 8px 0 0 rgb(0 0 0 / 20%)",
      addresBarBackground: "#0F1D19",
      addresBarColor: "#fff",
      addresBarSquaresColor: "#0F1D19",
      addresBarSquaresBorderColor: "#fff",
      addresBarSquaresBoxShadow: "none",
      dashboardBackground: "url(./pixels.svg) top left",
      text: {
        primary: "#FFFFFF",
        secondary: "#5c5a57",
        barColor: "#FFFFFF",
      },
      button: {
        text: "#FFFFFF",
        background: "#000000",
      },
      link: {
        text: "teal",
        opacity: 1,
      },
    },
    font: "Tinos",
  },
  browso98: {
    id: "T_007",
    name: "Browso 98",
    colors: {
      primary: "#FFF3DD",
      secondary: "#142C69",
      windowColor: "#FFFFFF",
      background: "#142C69",
      boxShadow: "FFFFFF",
      barColor: "#142C69",

      bodyColor: "#008081",
      bodyBackground: "#008081 url('./pixels-dark.svg') top left",
      containerWindowColor: "#C6CECF",
      menuBackgroundColor: "#C6CECF",
      svgIconColor: "#191516",
      menuBorderColor: "#4E5252",
      menuBoxShadow: "inset 1px 1px 0 0 #fff, 0 8px 0 0 rgb(0 0 0 / 20%)",
      addresBarBackground: "#142C69",
      addresBarColor: "#fff",
      addresBarSquaresColor: "#C6CECF",
      addresBarSquaresBorderColor: "#4E5252",
      addresBarSquaresBoxShadow: "inset 1px 1px 0 0 #fff",
      dashboardBackground: "url(./pixels-light.svg) top left",
      text: {
        primary: "#142C69",
        secondary: "#5c5a57",
        barColor: "#FFFFFF",
      },
      link: {
        text: "#0d47a1",
        opacity: 0.8,
      },
    },
    font: "Ubuntu",
  },
  crystalMaze: {
    id: "T_007",
    name: "Crystal Maze",
    colors: {
      primary: "#142C69",
      secondary: "#142C69",
      windowColor: "#FFFFFF",
      background: "#142C69",
      boxShadow: "FFFFFF",
      barColor: "#FFFFFF",

      bodyColor: "#dfe0f5",
      bodyBackground: "#dfe0f5 url('./pixels-dark.svg') top left",
      containerWindowColor: "#fff",
      menuBackgroundColor: "#fff",
      svgIconColor: "#142C69",
      menuBorderColor: "#142c69",
      menuBoxShadow: "4px 4px 0 0 #142c69",
      addresBarBackground: "#fff",
      addresBarColor: "#142C69",
      addresBarSquaresColor: "#fff",
      addresBarSquaresBorderColor: "#142C69",
      addresBarSquaresBoxShadow: "none",
      dashboardBackground: "url(./pixels-dark.svg) top left",
      text: {
        primary: "#fff",
        secondary: "#5c5a57",
        barColor: "#142C69",
      },
      link: {
        text: "#0d47a1",
        opacity: 0.8,
      },
    },
    font: "Ubuntu",
  },
  sunsetShore: {
    id: "T_007",
    name: "Sunset Shore",
    colors: {
      primary: "#142C69",
      secondary: "#142C69",
      windowColor: "#FFE1E7",
      background: "#FFE1E7",
      boxShadow: "#FFFFFF",
      barColor: "#FFE1E7",

      bodyColor: "#6B6BA9",
      bodyBackground: "#6B6BA9 url('./pixels-dark.svg') top left",
      containerWindowColor: "#FFE1E7",
      menuBackgroundColor: "#FFE1E7",
      svgIconColor: "#142C69",
      menuBorderColor: "#142c69",
      menuBoxShadow: "inset 1px 1px 0 0 #fff, 0 8px 0 0 rgb(0 0 0 / 20%)",
      addresBarBackground: "#FFE1E7",
      addresBarColor: "#142C69",
      addresBarSquaresColor: "#FFE1E7",
      addresBarSquaresBorderColor: "#142C69",
      addresBarSquaresBoxShadow: "inset 1px 1px 0 0 #fff",
      dashboardBackground: "url(./pixels-light.svg) top left",
      text: {
        primary: "#142C69",
        secondary: "#5c5a57",
        barColor: "#142C69",
      },
      link: {
        text: "#0d47a1",
        opacity: 0.8,
      },
    },
    font: "Ubuntu",
  },
};

export default theme;
