export const types = {
  // Sync
  FILL_SUMMARY_DATA: "FILL_SUMMARY_DATA",
  OPEN_ARTICLE: "OPEN_ARTICLE",
  CLOSE_ARTICLE: "CLOSE_ARTICLE",
  FILL_INFO_DATA: "FILL_INFO_DATA",
  TOGGLE_INFO_BOX: "TOGGLE_INFO_BOX",
  OPEN_INFO_BOX: "OPEN_INFO_BOX",
  SHOW_CUSTOM_INFO_DATA: "SHOW_CUSTOM_INFO_DATA",
  CLOSE_CUSTOM_INFO_DATA: "CLOSE_CUSTOM_INFO_DATA",
  // Async
  LOAD_CUSTOM_DATA_ASYNC: "LOAD_CUSTOM_DATA_ASYNC",
  LOAD_ARTICLE_DATA_ASYNC: "LOAD_ARTICLE_DATA_ASYNC",
  LOAD_SUMMARY_DATA_ASYNC: "LOAD_SUMMARY_DATA_ASYNC",
};
