export const types = {
  // Sync
  FILL_TILES_DATA: "FILL_TILES_DATA",
  UPDATE_ACTUAL_DATA: "UPDATE_ACTUAL_DATA",
  // Async
  FILL_INITIAL_DATA_ASYNC: "FILL_INITIAL_DATA_ASYNC",
  UPDATE_ACTUAL_DATA_ASYNC: "UPDATE_ACTUAL_DATA_ASYNC",
};
